services:
  frontend:
    build: ./frontend
    ports:
      - "8080:8080"
    environment:
      PORT: 8080
      VITE_AUTH_SERVICE_URL: http://auth-service:3001
      VITE_PRODUCT_SERVICE_URL: http://product-service:3000
      VITE_ORDER_SERVICE_URL: http://order-service:3002
      NODE_ENV: production
    depends_on:
      - auth-service
      - product-service
      - order-service

  auth-service:
    build: ./services/auth-service
    ports:
      - "3001:3001"
    environment:
      PORT: 3001
      MONGODB_URI: mongodb://auth-db:27017/auth
      JWT_SECRET: efrei_super_pass
      NODE_ENV: production
    depends_on:
      - auth-db

  product-service:
    build: ./services/product-service
    ports:
      - "3000:3000"
    environment:
      PORT: 3000
      MONGODB_URI: mongodb://product-db:27017/ecommerce
      JWT_SECRET: efrei_super_pass
      NODE_ENV: production
    depends_on:
      - product-db

  order-service:
    build: ./services/order-service
    ports:
      - "3002:3002"
    environment:
      PORT: 3002
      MONGODB_URI: mongodb://order-db:27017/orders
      JWT_SECRET: efrei_super_pass
      VITE_PRODUCT_SERVICE_URL: http://product-service:3000
      NODE_ENV: production
    depends_on:
      - order-db
      - product-service

  auth-db:
    image: mongo:6-jammy
    ports:
      - "27018:27017"

  product-db:
    image: mongo:6-jammy
    ports:
      - "27017:27017"

  order-db:
    image: mongo:6-jammy
    ports:
      - "27019:27017"